--- 
title: "StatPREP: Data-driven statistics"
author: "Daniel Kaplan"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
github-repo: statprep/statprep-book
description: "Notes for instructors when teaching StatPREP lessons"
always_allow_html: yes
---

# Teaching Data-driven Statistics {#intro}

Description, prediction, decision

Large and growing student interest in computer science and statistics. That growing interest is not simply a matter of new subjects receiving attention or of transient employment opportunities. The interest reflects systemic changes in the technical infrastructure of life and work in the US and the world due to the emergence of ubiquitous computing. Among other things, computing has led to an explosion in the availability of data and to the ability to explore systems at a greater level of complexity and a finer level of detail. Since computers always work with a mathematical representation of the world, the ability to construct and interpret such representations (aka “modeling”) is now a core part of research, commercial, industrial, medical, social, and government activities. Mathematical skills, particularly in applied math and statistics, are essential here.



1. Wrangling
2. Visualization
3. Statistical description
4. Prediction

## Pocket guide to StatPREP commands

See `Essential_statprep_command.key`. Maybe put a copy of it here, or a full-page version.
